# Generated by Django 3.0.3 on 2020-02-06 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sports',
            name='sport_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
